pkg_name: nengo_loihi
repo_name: nengo/nengo-loihi

travis_yml:
  python: 3.5.2
  global_vars:
    NENGO_VERSION: nengo
  jobs:
    - stage: basic
      script: emulator
    - script: static
    - stage: advanced
      script: emulator
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git#egg=nengo
    - script: hardware
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git#egg=nengo
        NXSDK_VERSION: 0.8.1
    - script: docs
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git#egg=nengo

ci_scripts:
  - template: docs
    pip_install:
      - git+https://github.com/abr/abr_control.git
      - $NENGO_VERSION
      - cython
  - template: test
    output_name: emulator
    pip_install:
      - nengo-dl
      - $NENGO_VERSION
      - jupyter
      - numpy
    coverage: true
    nengo_tests: true
  - template: hardware
    pip_install:
      - coverage
  - template: static
    pip_install:
      - flake8
    post_commands:
      - flake8 nengo_loihi
      - flake8 --ignore=E226,E703,W391,W503 docs
  - template: deploy

codecov_yml: {}
